//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Permission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public App_Permission()
        {
            this.Users = new HashSet<User>();
        }
    
        public int app_permission_id { get; set; }
        public int app_id { get; set; }
        public string cloud_uid { get; set; }
        public string cloud_pwd { get; set; }
        public string Permission_N { get; set; }
        public Nullable<int> admin { get; set; }
    
        public virtual App App { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
