//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.App_Permission = new HashSet<App_Permission>();
        }
    
        public int uid { get; set; }
        public string ad_uid { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string department { get; set; }
        public string Role { get; set; }
        public Nullable<int> active { get; set; }
        public Nullable<int> Department_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<App_Permission> App_Permission { get; set; }
        public virtual Department Department1 { get; set; }
    }
}
