//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Configuration;

    public partial class UserAccessEntities : DbContext
    {
        public UserAccessEntities()
            : base(GetConnectionString())
        {
        }
    
        public static string GetConnectionString()
        {
            string connectionString = Environment.ExpandEnvironmentVariables(
                     ConfigurationManager.AppSettings["SQLConnection"]);
            
            return connectionString;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<App> Apps { get; set; }
        public virtual DbSet<App_Permission> App_Permission { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
    
        public virtual ObjectResult<Find_A_UserIDs_AppPermission_Result> Find_A_UserIDs_AppPermission(string user_id)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Find_A_UserIDs_AppPermission_Result>("Find_A_UserIDs_AppPermission", user_idParameter);
        }
    }
}
